Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "Ubuntu-2004"
  config.disksize.size = '50GB'
  #config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "libvirt" do |kvm|
    kvm.memory = "8192"
    kvm.cpus = 8  
  end
  config.vm.provision "file", source: "./local.conf", destination: "local.conf"
  config.vm.provision "file", source: "./admin-openrc.sh", destination: "admin-openrc.sh"
  config.vm.provision "shell", privileged: false, path: "init.sh"
end
