Vagrant.configure("2") do |config|

  config.vm.box = "roboxes/ubuntu2004"
  config.vm.hostname = "Ubuntu-20.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "libvirt" do |kvm|
    kvm.memory = "8192"
    kvm.cpus = 8  
  end
  config.vm.provision "shell", path: "init.sh" 
end
